# Site
name: "imake-whm"
title: "imake-whm"
description: "iMake Innovation Center's Appreciation for Women's History Month"
logo: 'assets/images/branding.png'
favicon: 'assets/images/branding.png'
baseurl: /imake-whm
url: "https://imake-innovation-center.github.io/imake-whm/"
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  figure_1:
    name: Nkeiru Nkwocha
    display_name: Nkeiru Nkwocha
    avatar: /assets/images/nkeiru_nkwocha.png

  figure_2:
    name: Anna Timarong & Patrick Saade
    display_name: Anna Timarong & Patrick Saade
    #avatar: /assets/images/anna_patrick.png

  figure_3:
    name: Jonathan Lopez and Jeffery Dixon
    display_name: Jonathan Lopez and Jeffery Dixon
    #avatar: 

  figure_4:
    name: Cynthia Roman & Jaired Jawed
    display_name: Cynthia Roman & Jaired Jawed
    #avatar

  figure_5:
    name: Melissa Ruano
    display_name: Melissa Ruano
    avatar: /assets/images/melissa_ruano.png


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-redirect-from

jekyll_auth:
  whitelist:
    - jekyll-redirect-from
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. 
# Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
